version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: baffo
    main: ./cmd/baffo
    binary: baffo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    builds:
      - mustache

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  disable: true

release:
  github:
    owner: breml
    name: logstash-config
